apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "fastapi-logs-*"
    isDefault: false
    editable: false
    jsonData:
      timeField: "@timestamp"
      esVersion: 7.0.0
      logMessageField: "message"
      logLevelField: "level"
      interval: Daily
    version: 1 